-- MySQL Script generated by MySQL Workbench
-- Thu Mar 31 22:32:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Networks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Networks` (
  `ID_NETWORK` INT NOT NULL AUTO_INCREMENT,
  `BSSID` TEXT(17) NULL,
  `SSID` VARCHAR(45) NULL,
  UNIQUE INDEX `BSSID_UNIQUE` (`BSSID` ASC),
  PRIMARY KEY (`ID_NETWORK`),
  UNIQUE INDEX `idNetworks_UNIQUE` (`ID_NETWORK` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RSSI_GPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RSSI_GPS` (
  `RSSI` INT NULL,
  `GPS` VARCHAR(45) NULL,
  `ID_NETWORK` INT NULL,
  `ID_RSSI_GPS` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_RSSI_GPS`),
  INDEX `ID_NETWORK_idx` (`ID_NETWORK` ASC),
  CONSTRAINT `ID_NETWORK`
    FOREIGN KEY (`ID_NETWORK`)
    REFERENCES `mydb`.`Networks` (`ID_NETWORK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
